export const GET_TYPE = "GET_TYPE";
export const GET_SYMBOL = "GET_SYMBOL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const ADD_PRICE = "ADD_PRICE";
export const TOTAL_PRICE = "TOTAL_PRICE";

export const ADD_QUANTITY = "ADD_QUANTITY";

export const GET_QUANTITIES = "GET_QUANTITIES";
export const CHANGE_ATTRIBUTE = "CHANGE_ATTRIBUTE";

export const SET_OVERLAY_CART = "SET_OVERLAY_CART";

export const SET_CONST_ATTRIBUTES = "SET_CONST_ATTRIBUTES";
export const DELETE_CONST_ATTRIBUTES = "DELETE_CONST_ATTRIBUTES";

export const GET_PLP_PRODUCTS = "GET_PLP_PRODUCTS";
export const GET_PDP_PRODUCT = "GET_PDP_PRODUCT";
export const DELETE_PRODUCT_DETAILS = "DELETE_PRODUCT_DETAILS";
